name: Deploying Application

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  deploying-application:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "24"
      - name: Install dependencies
        run: npm install
      - name: Check style
        run: npm run eslint
      - name: Build
        run: npm run build
      - name: Test
        run: npm test
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: e2e tests
        run: npm run test:e2e
      - name: Deploy to this web on Render
        if: ${{github.event_name == 'push' && github.ref == 'refs/heads/main' && !contains(join(github.event.commits.*.message, ' '), '#skip')}}
        run: curl https://api.render.com/deploy/${{ secrets.RENDER_SERVICE_ID }}?key=${{ secrets.RENDER_API_KEY }}
      - name: Deploy Success Notification
        uses: rjstone/discord-webhook-notify@v2
        if: success()
        with:
          severity: info
          text: A new version of Pokedex deployed
          description: to https://pokedex-i2iu.onrender.com by ${{ github.event.head_commit.author.username }}
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
      - name: Build Failure Notification
        uses: rjstone/discord-webhook-notify@v2
        if: failure()
        with:
          severity: error
          text: Build failed
          description: commit ${{ github.event.head_commit.url }} by ${{ github.event.head_commit.author.username }} broke the build :(
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}

  tag_release:
    needs: [deploying-application]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: '0' 
          
      - name: Bump version and push tag
        if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message, ' '), '#skip') }}
        uses: anothrNick/github-tag-action@1.75.0 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
          DEFAULT_BUMP: patch

